export const RESULTS_SORTED = 'RESULTS_SORTED';
export const TALKS_READY = 'TALKS_READY';
export const UPDATED_DIMENSIONS = 'UPDATED_DIMENSIONS';
export const UPDATED_SEARCH_TEXT = 'UPDATED_SEARCH_TEXT';
export const VEHICLE_SELECTED = 'VEHICLE_SELECTED';
export const CLEAR_SELECTED_VEHICLE = 'CLEAR_SELECTED_VEHICLE';
export const PAGE_CHANGE = 'PAGE_CHANGE';